### ISSUE TITLE
How can i pull it into my OBS as a "Window Caputure"?

### ISSUE THREAD

**Issue by BroWei6657** [drweissbrot/csgo-hud#46]

**Comment by 42Firehawk** [comment]
While the standard use case for the hud is to use display capture, placing the hud over Counter Strike running in fullscreen windowed, I did test window capture and it worked simply by running the hud and then creating a new window capture to capture the hud itself. Though you may need to "reset" what window it is at each launch. Are you able to say what the issue itself is? (I.e. can you use window capture with other programs and not this one, and if so what issues you are running into) Otherwise I can't find issue with it currently.

**Comment by BroWei6657** [comment]
THX for your reply!!!
Acturally i can use the "Window Capture" correctly in other programs like CS:GO or WeChat, while i am using the hud i can't capture it.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "drweissbrot/csgo-hud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 下午5:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [drweissbrot/csgo-hud] How can i pull it into my OBS as a "Window Caputure"? (Issue #46)





 
While the standard use case for the hud is to use display capture, placing the hud over Counter Strike running in fullscreen windowed, I did test window capture and it worked simply by running the hud and then creating a new window capture to capture the hud itself. Though you may need to "reset" what window it is at each launch. Are you able to say what the issue itself is? (I.e. can you use window capture with other programs and not this one, and if so what issues you are running into) Otherwise I can't find issue with it currently.

**Comment by 42Firehawk** [comment]
So to make sure I am understanding properly: you can select the hud in window capture, but it doesn't show it within obs?

**Comment by BroWei6657** [comment]
yeasorry for my bad English :(-------- 原始邮件 --------发件人： 42Firehawk ***@***.***>日期： 2022年12月1日周四 傍晚6:24收件人： drweissbrot/csgo-hud ***@***.***>抄送： BroWei6657 ***@***.***>, Author ***@***.***>主    题： Re: [drweissbrot/csgo-hud] How can i pull it into my OBS as a "Window Caputure"? (Issue #46)
So to make sure I am understanding properly: you can select the hud in window capture, but it doesn't show it within obs?

**Comment by 42Firehawk** [comment]
Your English is perfectly fine, I just wanted to make sure I understood the issue properly. My best guess is that one of two things is happening. Either something is misconfigured in obs, or the hud is in its inactive state. 
When not actively in a demo or gotv, the hud changes to an inactive state to reduce visual clutter in menus. This is shown with 4 gray "hooks" in the corners of the screen with some transparency, which would be hard to see in the obs preview. The hud will show all details once a demo is started, which opens it up fully. If the hud is not showing anything while in that state (and the hud is visible on screen as well) then most likely the issue is with obs configuration itself. Can you check to see if you can figure out which of the two it is?

**Comment by BroWei6657** [comment]
I'm afraid the issue is not in these two points... It seems that nothing wrong with my OBS config and as you can see, the HUD works perfectly... So i really dont know what happend to my computer :(



By the way, I'm using a laptop which has two display card (maybe the issue related to that?), OBS and HUD are working on my NVIDIA display card.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "drweissbrot/csgo-hud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 晚上6:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [drweissbrot/csgo-hud] How can i pull it into my OBS as a "Window Caputure"? (Issue #46)





 
Your English is perfectly fine, I just wanted to make sure I understood the issue properly. My best guess is that one of two things is happening. Either something is misconfigured in obs, or the hud is in its inactive state.
 When not actively in a demo or gotv, the hud changes to an inactive state to reduce visual clutter in menus. This is shown with 4 gray "hooks" in the corners of the screen with some transparency, which would be hard to see in the obs preview. The hud will show all details once a demo is started, which opens it up fully. If the hud is not showing anything while in that state (and the hud is visible on screen as well) then most likely the issue is with obs configuration itself. Can you check to see if you can figure out which of the two it is?

**Comment by BroWei6657** [comment]
I'm now thinking that wether can we put the hud into a html so that we can pull it as a "Browser"?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "drweissbrot/csgo-hud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 晚上6:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [drweissbrot/csgo-hud] How can i pull it into my OBS as a "Window Caputure"? (Issue #46)





 
Your English is perfectly fine, I just wanted to make sure I understood the issue properly. My best guess is that one of two things is happening. Either something is misconfigured in obs, or the hud is in its inactive state.
 When not actively in a demo or gotv, the hud changes to an inactive state to reduce visual clutter in menus. This is shown with 4 gray "hooks" in the corners of the screen with some transparency, which would be hard to see in the obs preview. The hud will show all details once a demo is started, which opens it up fully. If the hud is not showing anything while in that state (and the hud is visible on screen as well) then most likely the issue is with obs configuration itself. Can you check to see if you can figure out which of the two it is?

**Comment by drweissbrot** [comment]
Gave Window Capture a try, on my machine OBS does capture the HUD, but also a black background instead of the transparency -- so I can't put the Window Capture over the Game Capture.

If you _really_ want to use Window Capture, you could _try_ adding a background to the HUD (e.g. add `background #0f0` before https://github.com/drweissbrot/csgo-hud/blob/75f4405b48c18727a3568f3b6f49dd40a85cd670/src/stylus/base.styl#L16), and then use a Color Key filter in OBS to filter out that background color.  
The background color would leak into all transparent elements of the HUD though, so definitely not ideal.

Using a browser source is honestly a genius idea. Would be quite a bit of work to convert this project to that approach, but I'm tempted :D

In the meantime, the only way I've ever used this HUD is a Display Capture, like @42Firehawk mentioned above.
